name: quant-tool-build

on:
  push:
    branches: [ "main" ]

jobs:
    build:
        # 后续可以改成自己的服务器
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3

        - name: docker build
          run: |
             touch quant-toolbox.tar.gz
             echo 1111 > quant-toolbox.tar.gz
#            docker build . --file Dockerfile -t quant-toolbox:v0.$GITHUB_RUN_NUMBER --platform=linux/amd64
#            docker save -o quant-toolbox.tar.gz quant-toolbox:v0.$GITHUB_RUN_NUMBER

        - uses: actions/upload-artifact@v3
          with:
            name: quant-toolbox.tar.gz
            path: ./quant-toolbox.tar.gz
    deploy:
        needs: [build]
        runs-on: ubuntu-latest

        steps:
        - uses: actions/download-artifact@v2
          with:
            name: quant-toolbox.tar.gz

        - name: deploy quant-toolbox
          env:
            HOST: ${{ secrets.TENCENT_HOST }}
            KEY: ${{ secrets.TENCENT_PRI_KEY }}
          run: |
            mkdir -p ~/.ssh/ && echo "$KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
            scp -o StrictHostKeyChecking=no -r quant-toolbox.tar.gz work@${HOST}:/home/work/software
